# Example OIDC authentication account
#
# [account ACCOUNT_SHORTNAME]
# 
# password_file = /etc/osg/tokens/ACCOUNT_SHORTNAME.pw
# 

# Example client credentials account
#
# [account ACCOUNT_SHORTNAME]
# 
# token_request_url = https://demo.scitokens.org/oauth2/token
# client_id = PROVIDED_CLIENT_ID
# client_secret = PROVIDED_CLIENT_SECRET
# 

# Example token description
#
# [token TOKEN_NAME]
# 
# account = ACCOUNT_SHORTNAME
# token_path = /etc/osg/tokens/ACCOUNT_SHORTNAME.TOKEN_NAME.token
#
# Optional:
#
# audience = <list of audiences to request>
# (For tokens used against an HTCondor-CE, set to <CE FQDN>:<CE PORT>)
#
# scope = <list of scopes to request>
#
# min_lifetime = <minimum lifetime in seconds to remain in token>
#  (default: get a new token every time the timer runs)
